MEX       = mex
MUMPS_DIR = $(HOME)/MUMPS_4.9.2

LMETISDIR = $(HOME)/METIS/metis
LMETIS = -L$(LMETISDIR) -lmetis
LPORDDIR = $(MUMPS_DIR)/PORD/lib
LPORD = -L$(LPORDDIR) -lpord
LORDERINGS = $(LPORD) $(LMETIS)

LIBSEQ  = -L$(MUMPS_DIR)/libseq -lmpiseq

LIBBLAS = -lblas

LIBFORT = /opt/intel80/lib/libifcore.a /opt/intel80/lib/libifport.a /opt/intel80/lib/libirc.a

OPTC    = -O
